<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>جهازك تحت الاختراق!</title>
    <style>
        body {
            text-align: center;
            font-family: Arial, sans-serif;
            background-color: black;
            color: white;
            display: flex;
            flex-direction: column;
            justify-content: center;
            height: 100vh;
            transition: background-color 0.1s;
        }
        h1 {
            color: red;
            font-size: 3em;
            opacity: 0;
            transition: opacity 0.5s ease-in-out;
        }
        p {
            font-size: 1.5em;
            opacity: 0;
            transition: opacity 1s ease-in-out;
        }
        #countdown {
            font-size: 2.5em;
            color: yellow;
            font-weight: bold;
        }
    </style>
    <script>
        function startPrank() {
            let count = 2; // العد التنازلي يبدأ من 2 ثانية
            let countdownElement = document.getElementById("countdown");
            let interval = setInterval(() => {
                countdownElement.innerText = count;
                count--;
                if (count < 0) {
                    clearInterval(interval);
                    document.getElementById("warning").style.opacity = 1;
                    document.getElementById("message").style.opacity = 1;
                    flashScreen();
                }
            }, 600); // تسريع العد التنازلي
        }

        function flashScreen() {
            let flash = setInterval(() => {
                document.body.style.backgroundColor = document.body.style.backgroundColor === "black" ? "red" : "black";
            }, 200); // وميض أسرع كل 0.2 ثانية
            setTimeout(() => {
                clearInterval(flash);
                document.body.style.backgroundColor = "black";
            }, 3000); // التوقف بعد 3 ثوانٍ
        }
    </script>
</head>
<body onload="startPrank()">
    <h1 id="warning">جهازك تحت الاختراق!<br> تم سحب كامل البيانات!</h1>
    <p id="message">تم الاستيلاء على جميع بياناتك، استعد للأسوأ!</p>
    <p>سيتم تنفيذ العملية خلال: <span id="countdown">2</span> ثانيتين</p>
</body>
</html>
